Repository vaadin/vaadin-grid-flow, pull requests merged in 2019-02, with the labels that each got.

#505 Test fixes
  vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/contextmenu/ContextMenuGridIT.java
  vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
Labels: in progress

#530 Update to Flow 1.4-SNAPSHOT
  pom.xml
Labels: in progress

#528 Bump to 3.1-SNAPSHOT and Flow 1.5-SNAPSHOT
  pom.xml
  vaadin-grid-flow-demo/pom.xml
  vaadin-grid-flow-integration-tests/pom.xml
  vaadin-grid-flow-testbench/pom.xml
  vaadin-grid-flow/pom.xml
Labels: in progress

#500 Correct setTarget behavior for null
  vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/contextmenu/ContextMenuGridPage.java
  vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/contextmenu/ContextMenuGridIT.java
  vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
  vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridComponentRendererIT.java
  vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridExpandCollapseRecursivelyIT.java
  vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/contextmenu/GridContextMenu.java
  vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/contextmenu/GridContextMenuTest.java
Labels: in progress

#520 Update vaadin-grid-flow-selection-column width
  vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.html
Labels: in progress

#543 Fix typos in tests
  vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
  vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridView.java
  vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/HiddenColumnPage.java
Labels: in progress

#504 Add extended context menu opened change listener.
  vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
  vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/contextmenu/ContextMenuGridPage.java
  vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/contextmenu/ContextMenuGridIT.java
  vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
  vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/contextmenu/GridContextMenu.java
  vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Labels: waiting for author

#517 Fixes #516 and #515
  vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Labels: waiting for author

#562 2.1.7 cherry picks
  src/main/java/com/vaadin/flow/component/grid/editor/EditorImpl.java
  src/main/resources/META-INF/resources/frontend/gridConnector.js
  src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.html
  src/test/java/com/vaadin/flow/component/grid/demo/GridView.java
  src/test/java/com/vaadin/flow/component/grid/editor/EditorImplTest.java
  src/test/java/com/vaadin/flow/component/grid/it/GridEditorFocusIT.java
  src/test/java/com/vaadin/flow/component/grid/it/GridEditorFocusPage.java
  src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
  src/test/java/com/vaadin/flow/component/grid/it/HiddenColumnPage.java
  src/test/java/com/vaadin/flow/component/grid/testbench/GridElement.java
  src/test/java/com/vaadin/flow/component/grid/testbench/GridTHTDElement.java
  src/test/java/com/vaadin/flow/component/grid/testbench/GridTRElement.java
Labels: in progress

#510 fix connector so as it works in Polymer 3
  vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Labels: in progress, npm
