Repository vaadin/vaadin-grid-flow, pull requests merged in 2019-05, with the labels that each got.

#633 Make TB artifactId consistent with other components
  vaadin-grid-flow-integration-tests/pom.xml
  vaadin-grid-flow-testbench/pom.xml
Labels: in progress

#637 Add polyfill for iOS devices
  vaadin-grid-flow/pom.xml
  vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Labels: in progress

#639 Pin dependency versions
  vaadin-grid-flow/pom.xml
Labels: in progress

#641 Add prerelease repo to be able to release Grid properly
  pom.xml
Labels: in progress

#621 New TreeGrid demo changes
  vaadin-grid-flow-demo/pom.xml
  vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/treegrid/demo/TreeGridDemo.java
  vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/treegrid/demo/data/AccountData.java
  vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/treegrid/demo/data/DepartmentData.java
  vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/treegrid/demo/entity/Account.java
  vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/treegrid/demo/entity/Department.java
  vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/treegrid/demo/service/AccountService.java
Labels: in review

#642 Fix the HeaderFooterTest to not use common package
  vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java
Labels: in progress

#622 New Grid demo changes
  vaadin-grid-flow-demo/pom.xml
  vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
  vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/ItemGenerator.java
  vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/PeopleGenerator.java
  vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/data/CountryData.java
  vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/data/CustomerData.java
  vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/data/StatesData.java
  vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/data/TaskData.java
  vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/entity/Customer.java
  vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/entity/Task.java
Labels: in review

#645 Update webjar dependencies
  vaadin-grid-flow/pom.xml
Labels: in progress

#647 Update Grid version and use property for context menu version
  pom.xml
  vaadin-grid-flow/pom.xml
  vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Labels: in progress

#650 Fix connector when runing in bower mode for Safari and FF
  vaadin-grid-flow-demo/pom.xml
  vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Labels: in progress, npm

#653 Remove vaadin-components-testbench
  vaadin-grid-flow-testbench/pom.xml
Labels: in progress
