Repository vaadin/vaadin-grid-flow, pull requests merged in 2019-03, with the labels that each got.

#569 Add vaadin-grid-flow-selection-column component for P3
  vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.js
Labels: npm

#583 IT for focusing components inside grid cells using keyboard (#564)
  src/test/java/com/vaadin/flow/component/grid/it/GridDelegateFocusToComponentIT.java
  src/test/java/com/vaadin/flow/component/grid/it/GridDelegateFocusToComponentPage.java
Labels: in progress

#582 IT for focusing components inside grid cells using keyboard (#564)
  src/test/java/com/vaadin/flow/component/grid/it/GridDelegateFocusToComponentIT.java
  src/test/java/com/vaadin/flow/component/grid/it/GridDelegateFocusToComponentPage.java
Labels: in progress

#581 IT for focusing components inside grid cells using keyboard (#564)
  vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridDelegateFocusToComponentPage.java
  vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridDelegateFocusToComponentIT.java
Labels: in review unscoped

#592 Add a test tht checks that flow-component-renderer doesn't throw if t…
  vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/TextInsideComponentRendererPage.java
  vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/TextInsideComponentRendererIT.java
Labels: in progress

#591 Add a test tht checks that flow-component-renderer doesn't throw if t…
  vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/TextInsideComponentRendererPage.java
  vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/TextInsideComponentRendererIT.java
Labels: in progress

#598 Revert "Add a test tht checks that flow-component-renderer doesn't th…
  vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/TextInsideComponentRendererPage.java
  vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/TextInsideComponentRendererIT.java
Labels: in progress

#599 IT for focusing components inside grid cells using keyboard (flow #41…
  src/test/java/com/vaadin/flow/component/grid/it/TextInsideComponentRendererIT.java
  src/test/java/com/vaadin/flow/component/grid/it/TextInsideComponentRendererPage.java
Labels: in progress

#596 Bump context-menu version and update tests
  pom.xml
  vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/contextmenu/GridContextMenuTest.java
Labels: in review unscoped

#602 Change the validator logic in the demo
  vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
Labels: to be cherry picked
